### ISSUE TITLE
Import issue with pydantic

### ISSUE THREAD

**Issue by allnash** [Modern-Treasury/modern-treasury-python#142]
Hello,

The following code has issues and we are unable to run our system due to import issues
```
from pydantic.fields import ModelField
from pydantic.typing import get_args, is_union, get_origin, is_literal_type
from pydantic.datetime_parse import parse_date
```

Error
```
ImportError: cannot import name 'ModelField' from 'pydantic.fields'
```

**Comment by rattrayalex** [comment]
Hi @allnash,

Sorry about this; you may need to downgrade your `pydantic` dependency to v1. We have an upcoming release to specify this.

**Comment by allnash** [comment]
A workaround is to add the following deps
`pydantic = "==1.10.7"`

**Comment by rattrayalex** [comment]
This has been fixed; the library now requires pydantic <2.
