### ISSUE TITLE
"Idempotency-Key" specified via extra_headers gets overwritten by framework code

### ISSUE THREAD

**Issue by willywu** [Modern-Treasury/modern-treasury-python#70]
I was hoping to take advantage of the "Idempotency-Key" documented in https://docs.moderntreasury.com/reference/idempotent-requests, but it wasn't as straight forward as:
```
client = ModernTreasury(
  organization_id="...",
  api_key="...",
)
client.payment_orders.create(
  ...,
  extra_headers={"Idempotency-Key": "mykey123"},
)
```

Because it looks like the "extra_headers" parameter gets set on the "headers" field of the "options" in https://github.com/Modern-Treasury/modern-treasury-python/blob/c8d1c053e07c312055275a64f2b14a5765cb2613/src/modern_treasury/resources/payment_orders/payment_orders.py#L254

But there's a different section of code that looks for `options.idempotency_key` to be set, and it overwrites any value of the "Idempotency-Key" header value with its own `self._idempotency_key()`:
https://github.com/Modern-Treasury/modern-treasury-python/blob/c8d1c053e07c312055275a64f2b14a5765cb2613/src/modern_treasury/_base_client.py#L336-L339

Is there a way to set our own "Idempotency-Key", maybe as an undocumented option?

**Comment by rattrayalex** [comment]
Sorry about this @willywu ! This is a bug, and we hope to get it fixed soon, both by adding an `idempotency_key` kwarg and by reading a manually-provided `"Idempotency-Header"` if it exists.

**Comment by willywu** [comment]
Cool, thanks for the confirmation.  Both of those solutions sound great!

In the meantime, after creating a client, I'm setting `client._idempotency_key` to a custom-function as a workaround.  :)

**Comment by cleb11** [comment]
`1.10` has been released and this issue should be resolved!
