### ISSUE TITLE
Cannot configure httpx.Client.limits for custom size of connection pool

### ISSUE THREAD

**Issue by louis-jaris** [Modern-Treasury/modern-treasury-python#72]
`httpx` is exposing the kwarg `limits` in `httpx.Client` to configure the underlying size of the connection pool.

Documentation https://www.python-httpx.org/advanced/#pool-limit-configuration

This library does not offer its user the possibility to specifically configure an `httpx.Limit` to use with it.

----

**Suggestion:**

Add some sort of configuration that gives the ability to the library user to easily configure the properties of the underlying connection pool.

----

Current workaround:

```python
import httpx
import modern_treasury

modern_treasury = modern_treasury.ModernTreasury(
    api_key="API_KEY",
    organization_id="ORG_ID"
)

standard_client = modern_treasury._client
custom_client = httpx.Client(
    base_url=standard_client.base_url,
    timeout=standard_client._timeout,
    headers=standard_client.headers,
    limits=httpx.Limits(max_connections=120, max_keepalive_connections=100, keepalive_expiry=20)
)

# Override old client with the customized one
modern_treasury._client = custom_client

# Use the library like before
modern_treasury.ledger_accounts.list()
```

**Comment by cleb11** [comment]
@louis-jaris `1.10` has been released and this issue should be resolved!
