### ISSUE TITLE
Response objects does not expose rate limit information

### ISSUE THREAD

**Issue by louis-jaris** [Modern-Treasury/modern-treasury-python#80]
Modern Treasury is using the concept of rate limit: https://docs.moderntreasury.com/reference/rate-limits

This library does not expose the rate limit information returned by Modern Treasury in the headers `X-Rate-Limit-Limit` and `X-Rate-Limit-Remaining`, making impossible dynamic concurrent calls to MT API.

**Comment by RobertCraigie** [comment]
Hey Louis, I'm really sorry we missed this - looks like our notifications weren't setup properly for this repository.

We already handle the [custom retry logic](https://docs.moderntreasury.com/reference/rate-limits#custom-retry-logic) case mentioned in the documentation. Are you interested in accessing these headers to support [staggering API calls](https://docs.moderntreasury.com/reference/rate-limits#staggering-api-calls)?
